LOCAL_PATH := $(call my-dir)
LOCAL_SRC_FILES := medialibrary.c
LOCAL_MODULE    := mla
LOCAL_MODULE_FILENAME := libmla
LOCAL_LDLIBS    := -L$(OUT_LIB_DIR)
LOCAL_C_INCLUDES := -l$(MEDIALIBRARY_INCLUDE_DIR) -l$(SQLITE3_DIR)
include $(BUILD_SHARED_LIBRARY)